### PR TITLE
Small changes to follow Some java rules better and remove redundant task...

### PR DESCRIPTION
**Pull request by ProjectBarks**
Small changes didn't too too much editing but made it more to Java rule specs and simplified the coding to remove redundant checks and simplify your life.

~Lovely Plugin

### CODE REVIEW

**Comment by andune** [comment]
I looked through this, much of this is style choices. While I haven't gotten around to setting up Heimdall with Sonar yet or fixing some legacy uglies as a result of Eclipse (like those blasted tabs), others are actually my style choices, likely a holdover from being an old-school C dev. Nonetheless, it's my project so those style choices are mine to make. ;)

Primary differences in style from the choices you've implemented in this pull request (looks like the Sun-published Java standards) :
- I don't use {}'s for single-statement if/else statements in most cases. There are all sorts of good reasons to do so, I know, but stylistically I'm attached to the lack of braces for single statements. Oddly though, I'm not 100% consistent but I'm OK with that (sometimes I add them on long if/else ladders if I feel it adds clarity). I'd be willing to give on this one if it meant code contributions from someone else in the future, other than just style changes.
- if/else ladders: I break else statements on separate lines, I've never liked the "} else {" syntax. Doesn't bother me for try/catch.
- logging; I see the changing of logging statements to use the log(Level.) format. I have a personal preference for the slf4j-style methods that don't require the inclusion of an additional Level class just to log. I actually have an abstract implementation in anduneCommonLib I've been slowly rolling into my projects, I haven't updated Heimdall yet.

I see lots of changes I could take or leave, meaning it doesn't matter one way or the other to me: moving enums to the end of classes, switch indentation and some others.

I see intermixed in all the mass-reformatting some helpful code changes too, which would be great to be able to incorporate without having to accept a bunch of code reformatting with it.

I appreciate the time put into making the changes and pull request: much of this looks like it could have been the work of simply asking the IDE to auto-reformat the code, some of this seems to obviously have been done by hand. If you'd like to separate the non-style code changes from style choices, I'd be happy to incorporate those.

Also, if you have plans to contribute to the project long term please feel free to tell me what you have in mind here. Since I'm no longer nearly as active as I once was in the Minecraft dev community, I might be willing to give up a few style choices if it meant there would be additional help on the project with new features contributed from other devs like yourself.

Since it's only been myself working on it previously, I haven't published my own coding standards guide. But I do use Sonar on some of my other projects (http://www.andune.com:9000/) and can bring this project under Sonar reports and document my few style choice changes from the default "Sonar way with Findbugs" profile, so you'll know what my code preferences are for code contributions.

**Comment by Leopere** [comment]
I'm glad you two have gotten acquainted. Hopefully things work out here.

**Comment by andune** [comment]
I never received a response to my request, but following up on this ticket.

I'm happy to accept help on the project, but as previously stated, would prefer discreet pull requests vs. massive code style reformatting requests. As I mentioned, my code style preferences are published up on Sonar so you are welcome to pull those rules and use them in your own local Sonar checks.

I'm closing this ticket but will happily accept discreet pull requests for individual feature enhancements or fixes.

**Comment by Leopere** [comment]
Apologies about this things for my attempt for this project kind of melted.

**Pull request closed without merging**
